#!/usr/bin/env bash

set -e -o pipefail

NAMESPACE=${NAMESPACE:-fleet-local}
FROM=${FROM:-1}
TO=${TO:-10}
if [ "$FROM" -ge "$TO" ]; then
    TO=$((FROM + 10))
fi

for i in $(seq "$FROM" "$TO"); do
    cp fleet.yaml helm/fleet.yaml
    yq eval ".namespace = \"foo-$i\"" -i helm/fleet.yaml
    fleetcli -n "$NAMESPACE" apply "foo-$i" helm
done
