#!/usr/bin/env bash

set -e -o pipefail

NAMESPACE=${NAMESPACE:-fleet-local}

for i in $(seq 1 10); do
    cp fleet.yaml helm/fleet.yaml
    yq eval ".namespace = \"foo-$i\"" -i helm/fleet.yaml
    fleetcli -n "$NAMESPACE" apply "foo-$i" helm
done
