#!/bin/bash

set -euxo pipefail

docker_mirror=${DOCKER_MIRROR:-}
extra_k3d_args="${EXTRA_K3D_ARGS:-}"
name=${1-upstream} # cluster name
i=${2-0}           # port offset
net=${3}           # network name

args="${EXTRA_K3D_ARGS}"
if [ -n "$docker_mirror" ]; then
  TMP_CONFIG="$(mktemp)"
  trap "rm -f $TMP_CONFIG" EXIT

  cat << EOF > "$TMP_CONFIG"
mirrors:
  "docker.io":
      endpoint:
            - $docker_mirror
EOF
  args="$args --registry-config $TMP_CONFIG"
fi

args="$args --network $net --no-lb --k3s-arg=--disable=servicelb,metrics-server,traefik@server:* --kubeconfig-switch-context=false"

k3d cluster create "$name" --servers 1 --api-port $(( 36443 + i )) $args
