#!/usr/bin/env bash

./20.sh 10

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update

helm upgrade --install -n monitoring --create-namespace \
    --version 25.0.0 \
    --values prometheus-values.yaml \
    prometheus prometheus-community/prometheus

helm upgrade --install -n monitoring --create-namespace \
    --version 6.60.1 \
    -f grafana-values.yaml \
    grafana grafana/grafana

kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" |
    base64 --decode
echo

echo "kubectl port-forward --namespace default svc/grafana 3000:80"
echo "kubectl port-forward --namespace default svc/prometheus-server 9090:80"
